version: '3'

services:
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb
        container_name: mariadb
        volumes:
            - volumedb:/var/lib/mysql/
        restart: on-failure
        networks:
            - mynet
        env_file:
            - ./.env
    wordpress:
        depends_on:
            - mariadb
            - redis
            - vsftpd
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        volumes:
            - volumewpng:/var/www/html
        restart: on-failure
        networks:
            - mynet
        env_file:
            - ./.env
    nginx:
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        container_name: nginx
        volumes:
            - volumewpng:/var/www/html
        ports:
            - "443:443"
        restart: on-failure
        networks:
            - mynet
        env_file:
            - ./.env
    redis:
        build:
            context: ./requirements/bonus/redis
            dockerfile: Dockerfile
        image: redis
        container_name: redis
        restart: on-failure
        networks:
            - mynet
    vsftpd:
        build:
            context: ./requirements/bonus/ftp
            dockerfile: Dockerfile
        image: vsftpd
        container_name: vsftpd
        volumes:
            - volumewpng:/srv/ftp/
        restart: on-failure
        networks:
            - mynet
        ports:
            - "21:21"
    adminer:
        build:
            context: ./requirements/bonus/adminer
            dockerfile: Dockerfile
        image: adminer
        container_name: adminer
        volumes:
            - volumewpng:/var/www/html
        restart: on-failure
        networks:
            - mynet
    cadvisor:
        build:
            context: ./requirements/bonus/cadvisor
            dockerfile: Dockerfile
        image: cadvisor
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - "4444:8080"
        restart: on-failure
        networks:
            - mynet
    website:
        build:
            context: ./requirements/bonus/website
            dockerfile: Dockerfile
        image: website
        container_name: website
        volumes:
            - volumewpng:/var/www/html
        ports:
            - "2002:80"
        restart: on-failure
        networks:
            - mynet

volumes:
    volumewpng:
        driver: local
        driver_opts:
            device: /home/aoudija/data/wpng
            type: none
            o: bind
    volumedb:
        driver: local
        driver_opts:
            device: /home/aoudija/data/db
            type: none
            o: bind
networks:
    mynet:
        name: mynet